version: '3.8'

services:
  postgresql-db:
    image: postgres:15-alpine
    container_name: leaderboard-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./db-volume:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=somesecret
      - POSTGRES_DB=leaderboard
  redis:
    image: redis:7.0.11-alpine
    container_name: leaderboard-redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - ./cache-data:/data
  rest-server:
    build: .
    container_name: rest-server
    depends_on:
      - postgresql-db
      - redis
    ports:
      - 8080:8080
    environment:
      - DB_HOST=leaderboard-db
      - DB_NAME=leaderboard
      - DB_PASSWORD=somesecret
      - DB_PORT=5432
      - REDIS_HOST=leaderboard-redis
      - REDIS_PORT=6379
      - REST_PORT=8080
